"""add_attachment_path_to_reports

Revision ID: 1240ba4126fa
Revises: c32123066bbc
Create Date: 2026-08-04 13:09:56.108687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1240ba4126fa'
down_revision: Union[str, Sequence[str], None] = 'c32123066bbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_reports', sa.Column('attachment_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community_reports', 'attachment_path')
    # ### end Alembic commands ###
