"""add job scam check columns

Revision ID: 34a3212cbf4a
Revises: c74c832138ad
Create Date: 2026-07-29 15:54:27.144454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a3212cbf4a'
down_revision: Union[str, Sequence[str], None] = 'c74c832138ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_scam_checks', sa.Column('requests_advance_payment', sa.Boolean(), nullable=True))
    op.add_column('job_scam_checks', sa.Column('salary_unrealistic', sa.Boolean(), nullable=True))
    op.add_column('job_scam_checks', sa.Column('missing_company_info', sa.Boolean(), nullable=True))
    op.add_column('job_scam_checks', sa.Column('urgent_hiring_language', sa.Boolean(), nullable=True))
    op.add_column('job_scam_checks', sa.Column('grammar_quality_score', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_scam_checks', 'grammar_quality_score')
    op.drop_column('job_scam_checks', 'urgent_hiring_language')
    op.drop_column('job_scam_checks', 'missing_company_info')
    op.drop_column('job_scam_checks', 'salary_unrealistic')
    op.drop_column('job_scam_checks', 'requests_advance_payment')
    # ### end Alembic commands ###
