"""add learning hub tables

Revision ID: 47ae72eba293
Revises: 34a3212cbf4a
Create Date: 2026-07-29 17:15:41.144476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47ae72eba293'
down_revision: Union[str, Sequence[str], None] = '34a3212cbf4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_tiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_bn', sa.String(length=100), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('unlock_requirement', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('title_bn', sa.String(length=200), nullable=False),
    sa.Column('content_en', sa.Text(), nullable=False),
    sa.Column('content_bn', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tier_id'], ['lesson_tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('question_en', sa.Text(), nullable=False),
    sa.Column('question_bn', sa.Text(), nullable=False),
    sa.Column('options_en', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('options_bn', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_option_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_lesson_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('quiz_score', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_lesson_progress')
    op.drop_table('quiz_questions')
    op.drop_table('lessons')
    op.drop_table('lesson_tiers')
    # ### end Alembic commands ###
