"""add log scanner tables

Revision ID: 528eb216a14b
Revises: 47ae72eba293
Create Date: 2026-08-01 10:47:07.939038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '528eb216a14b'
down_revision: Union[str, Sequence[str], None] = '47ae72eba293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_attacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attack_name', sa.String(length=150), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attack_name')
    )
    op.create_table('log_attack_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attack_id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['attack_id'], ['log_attacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_behavior_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attack_id', sa.Integer(), nullable=False),
    sa.Column('attack_name', sa.String(length=150), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attack_id'], ['log_attacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_scan_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('log_type', sa.String(length=20), nullable=True),
    sa.Column('total_findings', sa.Integer(), nullable=False),
    sa.Column('dangerous_findings', sa.Integer(), nullable=False),
    sa.Column('overall_risk_level', sa.String(length=20), nullable=False),
    sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_solutions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attack_id', sa.Integer(), nullable=False),
    sa.Column('fix_description', sa.Text(), nullable=False),
    sa.Column('command', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['attack_id'], ['log_attacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_detected_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('attack_id', sa.Integer(), nullable=True),
    sa.Column('source_ip', sa.String(length=100), nullable=True),
    sa.Column('request_url', sa.String(length=500), nullable=True),
    sa.Column('evidence', sa.String(length=500), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('detection_type', sa.String(length=20), nullable=True),
    sa.Column('detected_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['attack_id'], ['log_attacks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['log_scan_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_detected_events')
    op.drop_table('log_solutions')
    op.drop_table('log_scan_sessions')
    op.drop_table('log_behavior_rules')
    op.drop_table('log_attack_patterns')
    op.drop_table('log_attacks')
    # ### end Alembic commands ###
