"""add phone, district, occupation, terms_accepted to users

Revision ID: b039ae6f4863
Revises: c1453fa8a2cf
Create Date: 2026-08-07 01:41:30.553779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b039ae6f4863'
down_revision: Union[str, Sequence[str], None] = 'c1453fa8a2cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('district_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('occupation', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('terms_accepted', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET terms_accepted = false WHERE terms_accepted IS NULL")
    op.alter_column('users', 'terms_accepted', nullable=False)
    op.create_foreign_key(None, 'users', 'districts', ['district_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'terms_accepted')
    op.drop_column('users', 'occupation')
    op.drop_column('users', 'district_id')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
