"""add districts, url_scans, community_reports, job_scam_checks tables

Revision ID: c74c832138ad
Revises: c04d3d2748a6
Create Date: 2026-07-28 14:28:06.565731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c74c832138ad'
down_revision: Union[str, Sequence[str], None] = 'c04d3d2748a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_en', sa.String(length=60), nullable=False),
    sa.Column('name_bn', sa.String(length=60), nullable=False),
    sa.Column('division', sa.String(length=60), nullable=False),
    sa.Column('centroid_lat', sa.String(length=30), nullable=True),
    sa.Column('centroid_lng', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('screenshot_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_scam_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('raw_post_text', sa.Text(), nullable=False),
    sa.Column('risk_score', sa.SmallInteger(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('url_scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('original_input', sa.Text(), nullable=False),
    sa.Column('resolved_url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('uses_https', sa.Boolean(), nullable=True),
    sa.Column('is_shortened', sa.Boolean(), nullable=True),
    sa.Column('has_login_keyword', sa.Boolean(), nullable=True),
    sa.Column('suspicious_tld', sa.Boolean(), nullable=True),
    sa.Column('risk_score', sa.SmallInteger(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_scans')
    op.drop_table('job_scam_checks')
    op.drop_table('community_reports')
    op.drop_table('districts')
    # ### end Alembic commands ###
